import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UserProvider } from "./context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//client component is on the tree leaf of the tree structure



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <UserProvider>
        <div>
          <Link href={"./todo"}>todo link</Link>
          <div>
          <Link href={"./todolist"}>todo List</Link>
          </div>
        </div>

        {children}
        </UserProvider>
      </body>
    </html>
  );
}
